---S-527323 Arpitha 01/29/2026---
USE ROLE SYSADMIN;
USE WAREHOUSE AAW_MATILLION_APP4_L;

UPDATE AAW.AAW_ELT.SRC_EXTRACT_CNTRL_TBL SET SOURCE_TABLE_NAME = 'GONG_ACTIVITY_WEEK' WHERE SRC_EXTRACT_CNTRL_GK = '100997';

UPDATE AAW.AAW_ELT.SRC_EXTRACT_CNTRL_TBL SET SOURCE_TABLE_NAME = 'GONG_ACTIVITY_WEEK_ACT' WHERE SRC_EXTRACT_CNTRL_GK = '101000';
