---S-527323 Arpitha 01/29/2026---
USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE TABLE SNOWFLAKE_LEARNING_DB.PUBLIC.customers (
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE
);
