name: Matillion Job Comparison
on:
  push:
    paths:
      - '**/*.ORCHESTRATION'
      - '**/*.TRANSFORMATION'
  pull_request:
    branches:
      - development
    paths:
      - '**/*.ORCHESTRATION'
      - '**/*.TRANSFORMATION'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  compare-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Get changed files
        id: changed-files
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep -E '\.(ORCHESTRATION|TRANSFORMATION)$' || true)
          else
            CHANGED_FILES=$(git diff --name-only origin/development...HEAD | grep -E '\.(ORCHESTRATION|TRANSFORMATION)$' || true)
          fi
          echo "Changed files: $CHANGED_FILES"
          echo "files=$CHANGED_FILES" >> $GITHUB_OUTPUT
      
      - name: Create and populate report
        id: create-report
        run: |
          mkdir -p ./reports
          echo "# Matillion Job Changes Report" > ./reports/report.md
          echo "Event: ${{ github.event_name }}" >> ./reports/report.md
          echo "Branch: ${{ github.ref_name }}" >> ./reports/report.md
          echo "" >> ./reports/report.md
          CHANGED_FILES="${{ steps.changed-files.outputs.files }}"
          if [ -z "$CHANGED_FILES" ]; then
            echo "No Matillion job files changed" >> ./reports/report.md
          else
            for FILE in $CHANGED_FILES; do
              echo "Analyzing $FILE..."
              if [ -f "$FILE" ]; then
                echo "### $FILE" >> ./reports/report.md
                echo '```' >> ./reports/report.md
                if [[ "${{ github.event_name }}" == "push" ]]; then
                  git show HEAD^:"$FILE" > old_version.json 2>/dev/null || echo "{}" > old_version.json
                  git show HEAD:"$FILE" > new_version.json
                else
                  git show origin/development:"$FILE" > old_version.json 2>/dev/null || echo "{}" > old_version.json
                  git show HEAD:"$FILE" > new_version.json
                fi
                python .github/scripts/matillion_compare.py old_version.json new_version.json >> ./reports/report.md
                echo '```' >> ./reports/report.md
                echo "" >> ./reports/report.md
              fi
            done
          fi
      
      - name: Create Issue for Direct Push
        if: github.event_name == 'push' && steps.changed-files.outputs.files != ''
        uses: actions/github-script@v6
        with:
          script: |
            try {
              const fs = require('fs');
              const report = fs.readFileSync('./reports/report.md', 'utf8');
              
              const issueData = {
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: '🔄 Matillion Job Changes Detected - Direct Push',
                body: report,
                labels: ['matillion-changes', 'direct-push']
              };
              
              await github.rest.issues.create(issueData);
            } catch (error) {
              core.setFailed('Failed to create issue: ' + error.message);
            }
      
      - name: Comment PR
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-file: ./reports/report.md
