name: Matillion Job Comparison

on:
  pull_request:
    branches:
      - development
    paths:
      - '**.json'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  compare-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Get changed files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only origin/development...HEAD | grep '\.json$' || true)
          echo "files=$CHANGED_FILES" >> $GITHUB_OUTPUT

      - name: Create and populate report
        id: create-report
        run: |
          mkdir -p ./reports
          
          echo "# Matillion Job Comparison Report" > ./reports/report.md
          echo "" >> ./reports/report.md
          
          CHANGED_FILES="${{ steps.changed-files.outputs.files }}"
          
          if [ -z "$CHANGED_FILES" ]; then
            echo "No JSON files changed" >> ./reports/report.md
          else
            for FILE in $CHANGED_FILES; do
              if [ -f "$FILE" ]; then
                # Save versions without debug output
                git show origin/development:"$FILE" > old_version.json 2>/dev/null || echo "{}" > old_version.json
                git show HEAD:"$FILE" > new_version.json
                
                echo "### $FILE" >> ./reports/report.md
                echo '```' >> ./reports/report.md
                python .github/scripts/matillion_compare.py old_version.json new_version.json >> ./reports/report.md
                echo '```' >> ./reports/report.md
                echo "" >> ./reports/report.md
              fi
            done
          fi

      - name: Comment PR
        if: always()
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-file: ./reports/report.md
